module KanjiDB.KanaTable where

import Protolude
import qualified Data.Text as T
import qualified Data.Map as Map
import Data.Char

toHiragana :: Text -> Text
toHiragana = T.map getH

getH 'ア' = 'あ'
getH 'ィ' = 'ぃ'
getH 'イ' = 'い'
getH 'ゥ' = 'ぅ'
getH 'ウ' = 'う'
getH 'ェ' = 'ぇ'
getH 'エ' = 'え'
getH 'ォ' = 'ぉ'
getH 'オ' = 'お'
getH 'カ' = 'か'
getH 'ガ' = 'が'
getH 'キ' = 'き'
getH 'ギ' = 'ぎ'
getH 'ク' = 'く'
getH 'グ' = 'ぐ'
getH 'ケ' = 'け'
getH 'ゲ' = 'げ'
getH 'コ' = 'こ'
getH 'ゴ' = 'ご'
getH 'サ' = 'さ'
getH 'ザ' = 'ざ'
getH 'シ' = 'し'
getH 'ジ' = 'じ'
getH 'ス' = 'す'
getH 'ズ' = 'ず'
getH 'セ' = 'せ'
getH 'ゼ' = 'ぜ'
getH 'ソ' = 'そ'
getH 'ゾ' = 'ぞ'
getH 'タ' = 'た'
getH 'ダ' = 'だ'
getH 'チ' = 'ち'
getH 'ヂ' = 'ぢ'
getH 'ッ' = 'っ'
getH 'ツ' = 'つ'
getH 'ヅ' = 'づ'
getH 'テ' = 'て'
getH 'デ' = 'で'
getH 'ト' = 'と'
getH 'ド' = 'ど'
getH 'ナ' = 'な'
getH 'ニ' = 'に'
getH 'ヌ' = 'ぬ'
getH 'ネ' = 'ね'
getH 'ノ' = 'の'
getH 'ハ' = 'は'
getH 'バ' = 'ば'
getH 'パ' = 'ぱ'
getH 'ヒ' = 'ひ'
getH 'ビ' = 'び'
getH 'ピ' = 'ぴ'
getH 'フ' = 'ふ'
getH 'ブ' = 'ぶ'
getH 'プ' = 'ぷ'
getH 'ヘ' = 'へ'
getH 'ベ' = 'べ'
getH 'ペ' = 'ぺ'
getH 'ホ' = 'ほ'
getH 'ボ' = 'ぼ'
getH 'ポ' = 'ぽ'
getH 'マ' = 'ま'
getH 'ミ' = 'み'
getH 'ム' = 'む'
getH 'メ' = 'め'
getH 'モ' = 'も'
getH 'ャ' = 'ゃ'
getH 'ヤ' = 'や'
getH 'ュ' = 'ゅ'
getH 'ユ' = 'ゆ'
getH 'ョ' = 'ょ'
getH 'ヨ' = 'よ'
getH 'ラ' = 'ら'
getH 'リ' = 'り'
getH 'ル' = 'る'
getH 'レ' = 'れ'
getH 'ロ' = 'ろ'
getH 'ヮ' = 'ゎ'
getH 'ワ' = 'わ'
getH 'ヲ' = 'を'
getH 'ン' = 'ん'
getH c = c
